### ISSUE TITLE
module numpy as no attribute 'float' did you mean 'cfloat'

### ISSUE THREAD

**Issue by ccrome** [fboulnois/stable-diffusion-docker#52]
Hi there,
  I'm trying to run the docker, and running into an issue.  Not quite sure why numpy wouldn't have 'float'.
the docker build went just fine, but when trying the example, it failed with the following:

Any idea how to diagnose that?

Thanks!

```
stable-diffusion-docker$ ./build.sh run --device cpu 'Andromeda galaxy in a bottle'
load pipeline start: 2023-01-04T20:22:12.012404
Downloading: 100%|██████████| 604/604 [00:00<00:00, 1.16MB/s]
Downloading: 100%|██████████| 342/342 [00:00<00:00, 158kB/s]
Downloading: 100%|██████████| 1.22G/1.22G [00:51<00:00, 23.4MB/s]
Downloading: 100%|██████████| 289/289 [00:00<00:00, 155kB/s]s/it]
Downloading: 100%|██████████| 492M/492M [00:21<00:00, 22.6MB/s]t]
Downloading: 100%|██████████| 525k/525k [00:00<00:00, 1.42MB/s]t]
Downloading: 100%|██████████| 472/472 [00:00<00:00, 259kB/s]s/it]
Downloading: 100%|██████████| 917/917 [00:00<00:00, 501kB/s]s/it]
Downloading: 100%|██████████| 1.06M/1.06M [00:00<00:00, 2.26MB/s]
Downloading: 100%|██████████| 778k/778k [00:00<00:00, 2.45MB/s]t]
Fetching 13 files:  77%|███████▋  | 10/13 [01:21<00:10,  3.42s/itrla
Downloading: 100%|██████████| 3.44G/3.44G [02:25<00:00, 23.7MB/s]
Downloading: 100%|██████████| 198M/198M [00:08<00:00, 22.4MB/s]it]
Downloading: 100%|██████████| 137M/137M [00:06<00:00, 22.6MB/s]it]
Fetching 13 files: 100%|██████████| 13/13 [04:04<00:00, 18.84s/it]
loaded models after: 2023-01-04T20:26:26.394072
Traceback (most recent call last):
  File "/usr/local/bin/docker-entrypoint.py", line 263, in <module>
    main()
  File "/usr/local/bin/docker-entrypoint.py", line 259, in main
    stable_diffusion_inference(pipeline)
  File "/usr/local/bin/docker-entrypoint.py", line 118, in stable_diffusion_inference
    result = p.pipeline(**remove_unused_args(p))
  File "/usr/local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion.py", line 250, in __call__
    latents = latents * np.float(self.scheduler.init_noise_sigma)
  File "/usr/local/lib/python3.10/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'. Did you mean: 'cfloat'?
```

**Comment by ccrome** [comment]
BTW, my host machine is:

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.10
Release:        22.10
Codename:       kinetic
```
I do have an 8GB GPU, but I don't have nvidia docker tools intalled, so just using CPU for now

**Comment by fboulnois** [comment]
Does this fix work for you? #51

**Comment by ccrome** [comment]
Yup, that fixed it!

Thanks!

**Comment by fboulnois** [comment]
Version 1.25.1 has the fixes. See https://github.com/fboulnois/stable-diffusion-docker/pull/51#issuecomment-1378181104 for more details.
