### ISSUE TITLE
Unable to Specify GPU

### ISSUE THREAD

**Issue by raybooysen** [fboulnois/stable-diffusion-docker#86]
Hi!

I'm utilising a system with multiple GPUs.  Running multiple instances of the docker container means I see errors as shown below.  How can I target specific GPUs on startup?

`loaded models after: 2023-07-06T08:39:39.643731
Traceback (most recent call last):
  File "/usr/local/bin/docker-entrypoint.py", line 307, in <module>
    main()
  File "/usr/local/bin/docker-entrypoint.py", line 303, in main
    stable_diffusion_inference(pipeline)
  File "/usr/local/bin/docker-entrypoint.py", line 153, in stable_diffusion_inference
    result = p.pipeline(**remove_unused_args(p))
  File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 688, in __call__
    prompt_embeds = self._encode_prompt(
  File "/usr/local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 382, in _encode_prompt
    prompt_embeds = self.text_encoder(
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 822, in forward
    return self.text_model(
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 740, in forward
    encoder_outputs = self.encoder(
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 654, in forward
    layer_outputs = encoder_layer(
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 383, in forward
    hidden_states, attn_weights = self.self_attn(
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 272, in forward
    query_states = self.q_proj(hidden_states) * self.scale
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)``

**Comment by fboulnois** [comment]
It isn't supported out of the box, but can limit the number of GPUs by modifying the [`GPU_ARG`](https://github.com/fboulnois/stable-diffusion-docker/blob/main/build.sh#L15) from `--gpus=all` to `--gpus=1` and passing the specific `device_ids` of the GPU following the Docker documentation here: https://docs.docker.com/compose/gpu-support/

**Comment by fboulnois** [comment]
Closing this issue since it is out-of-scope for this project.
